### ISSUE TITLE
Failed - No file

### ISSUE THREAD

**Issue by gaitat** [chuckfairy/THREE.WebMExporter#1]
Is there a limit on the number of frames that can be compiled or the size of the blob created?
I added a print statement in WebMExporter and got:
"Got to compile 4170 movie frames"
and then I print the size and the type of the blob and this is what I get:
"Size of movie blob: 250739803 video/webm"

But when I try to save the blob using createObjectURL (blob) I get a "Failed - No file".
This happens in Chrome (latest).

Also in the Chrome downloads window I see:
"The server could not find the file.
blob:file%3A///8993d68b-503d-4221-8e34-d1d09a3e7d82"

**Comment by chuckfairy** [comment]
Just tested with the webgl example with 4170 frames and was able to get it to compile and download (29.8mb). Using a loop with that many frames from what I just found out is a rather bad idea because Chrome ended up giving my kill page message. 

Are you using a web server or a file:// address?
Could you post some code?

**Comment by gaitat** [comment]
I am using a file:// to save.
I don't think it is a matter of code. I have followed your example very closely. I am using the `addFrame()` interface in my three.js `render()` function. 
When I record something small in length then everything is fine. It is only when I try to get a larger file, as my three.js animations are long, that it fails.

I am thinking that I am reaching some limit of the browser for size of blob files in which case they would have to be split up when they are created or when they are saved.

**Comment by chuckfairy** [comment]
Looking around I found thru this stackoverflow question http://stackoverflow.com/questions/28307789/is-there-any-limitation-on-javascript-max-blob-size. That the max blob size for Chrome is 500Mb. I don't think you're going past that though unless you think you are.  

I doubt this is the problem, but you should also try serving up the html thru apache or a server. 

This does bring up an important issue, that dataURLs can be very long. Another option that might work because you seem to be compiling the blob without problems would be to use the FileReader API. https://developer.mozilla.org/en-US/docs/Web/API/Blob. I'll have to look into this. Thanks for bringing this up.

**Comment by gaitat** [comment]
Well I could slice the Blob but I really wouldn't want to break the webm stream at some inappropriate place. I really don't know at this time what 'appropriate' means. Or do you think that it does not make a difference. I would like though to join the individual blobs in the end.

**Comment by chuckfairy** [comment]
Slicing the Blob could be an option, but it seems more of a problem with objectURL. You are getting the Blob created right? The issue is with the object URL? 

I think a Blob creation or dataURL creation from multi Blobs could a great idea. It could lessen the load on file compiling.
